CREATE TABLE `long_dragon`  (
     `eid` int NOT NULL AUTO_INCREMENT COMMENT '自增键',
     `create_time` datetime NOT NULL COMMENT '创建时间',
     `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
     `race_id` int NOT NULL COMMENT '比赛id',

     `sum3` int NULL DEFAULT NULL COMMENT '冠亚和3',
     `sum4` int NULL DEFAULT NULL COMMENT '冠亚和4',
     `sum5` int NULL DEFAULT NULL COMMENT '冠亚和5',
     `sum6` int NULL DEFAULT NULL COMMENT '冠亚和6',
     `sum7` int NULL DEFAULT NULL COMMENT '冠亚和7',
     `sum8` int NULL DEFAULT NULL COMMENT '冠亚和8',
     `sum9` int NULL DEFAULT NULL COMMENT '冠亚和9',
     `sum10` int NULL DEFAULT NULL COMMENT '冠亚和10',
     `sum11` int NULL DEFAULT NULL COMMENT '冠亚和11',
     `sum12` int NULL DEFAULT NULL COMMENT '冠亚和12',
     `sum13` int NULL DEFAULT NULL COMMENT '冠亚和13',
     `sum14` int NULL DEFAULT NULL COMMENT '冠亚和14',
     `sum15` int NULL DEFAULT NULL COMMENT '冠亚和15',
     `sum16` int NULL DEFAULT NULL COMMENT '冠亚和16',
     `sum17` int NULL DEFAULT NULL COMMENT '冠亚和17',
     `sum18` int NULL DEFAULT NULL COMMENT '冠亚和18',
     `sum19` int NULL DEFAULT NULL COMMENT '冠亚和19',
     `first_first` int NULL DEFAULT NULL,
     `first_second` int NULL DEFAULT NULL,
     `first_third` int NULL DEFAULT NULL,
     `first_fourth` int NULL DEFAULT NULL,
     `first_fifth` int NULL DEFAULT NULL,
     `first_sixth` int NULL DEFAULT NULL,
     `first_seventh` int NULL DEFAULT NULL,
     `first_eighth` int NULL DEFAULT NULL,
     `first_ninth` int NULL DEFAULT NULL,
     `first_tenth` int NULL DEFAULT NULL,
     `second_first` int NULL DEFAULT NULL,
     `second_second` int NULL DEFAULT NULL,
     `second_third` int NULL DEFAULT NULL,
     `second_fourth` int NULL DEFAULT NULL,
     `second_fifth` int NULL DEFAULT NULL,
     `second_sixth` int NULL DEFAULT NULL,
     `second_seventh` int NULL DEFAULT NULL,
     `second_eighth` int NULL DEFAULT NULL,
     `second_ninth` int NULL DEFAULT NULL,
     `second_tenth` int NULL DEFAULT NULL,
     `third_first` int NULL DEFAULT NULL,
     `third_second` int NULL DEFAULT NULL,
     `third_third` int NULL DEFAULT NULL,
     `third_fourth` int NULL DEFAULT NULL,
     `third_fifth` int NULL DEFAULT NULL,
     `third_sixth` int NULL DEFAULT NULL,
     `third_seventh` int NULL DEFAULT NULL,
     `third_eighth` int NULL DEFAULT NULL,
     `third_ninth` int NULL DEFAULT NULL,
     `third_tenth` int NULL DEFAULT NULL,
     `fourth_first` int NULL DEFAULT NULL,
     `fourth_second` int NULL DEFAULT NULL,
     `fourth_third` int NULL DEFAULT NULL,
     `fourth_fourth` int NULL DEFAULT NULL,
     `fourth_fifth` int NULL DEFAULT NULL,
     `fourth_sixth` int NULL DEFAULT NULL,
     `fourth_seventh` int NULL DEFAULT NULL,
     `fourth_eighth` int NULL DEFAULT NULL,
     `fourth_ninth` int NULL DEFAULT NULL,
     `fourth_tenth` int NULL DEFAULT NULL,
     `fifth_first` int NULL DEFAULT NULL,
     `fifth_second` int NULL DEFAULT NULL,
     `fifth_third` int NULL DEFAULT NULL,
     `fifth_fourth` int NULL DEFAULT NULL,
     `fifth_fifth` int NULL DEFAULT NULL,
     `fifth_sixth` int NULL DEFAULT NULL,
     `fifth_seventh` int NULL DEFAULT NULL,
     `fifth_eighth` int NULL DEFAULT NULL,
     `fifth_ninth` int NULL DEFAULT NULL,
     `fifth_tenth` int NULL DEFAULT NULL,
     `sixth_first` int NULL DEFAULT NULL,
     `sixth_second` int NULL DEFAULT NULL,
     `sixth_third` int NULL DEFAULT NULL,
     `sixth_fourth` int NULL DEFAULT NULL,
     `sixth_fifth` int NULL DEFAULT NULL,
     `sixth_sixth` int NULL DEFAULT NULL,
     `sixth_seventh` int NULL DEFAULT NULL,
     `sixth_eighth` int NULL DEFAULT NULL,
     `sixth_ninth` int NULL DEFAULT NULL,
     `sixth_tenth` int NULL DEFAULT NULL,
     `seventh_first` int NULL DEFAULT NULL,
     `seventh_second` int NULL DEFAULT NULL,
     `seventh_third` int NULL DEFAULT NULL,
     `seventh_fourth` int NULL DEFAULT NULL,
     `seventh_fifth` int NULL DEFAULT NULL,
     `seventh_sixth` int NULL DEFAULT NULL,
     `seventh_seventh` int NULL DEFAULT NULL,
     `seventh_eighth` int NULL DEFAULT NULL,
     `seventh_ninth` int NULL DEFAULT NULL,
     `seventh_tenth` int NULL DEFAULT NULL,
     `eighth_first` int NULL DEFAULT NULL,
     `eighth_second` int NULL DEFAULT NULL,
     `eighth_third` int NULL DEFAULT NULL,
     `eighth_fourth` int NULL DEFAULT NULL,
     `eighth_fifth` int NULL DEFAULT NULL,
     `eighth_sixth` int NULL DEFAULT NULL,
     `eighth_seventh` int NULL DEFAULT NULL,
     `eighth_eighth` int NULL DEFAULT NULL,
     `eighth_ninth` int NULL DEFAULT NULL,
     `eighth_tenth` int NULL DEFAULT NULL,
     `ninth_first` int NULL DEFAULT NULL,
     `ninth_second` int NULL DEFAULT NULL,
     `ninth_third` int NULL DEFAULT NULL,
     `ninth_fourth` int NULL DEFAULT NULL,
     `ninth_fifth` int NULL DEFAULT NULL,
     `ninth_sixth` int NULL DEFAULT NULL,
     `ninth_seventh` int NULL DEFAULT NULL,
     `ninth_eighth` int NULL DEFAULT NULL,
     `ninth_ninth` int NULL DEFAULT NULL,
     `ninth_tenth` int NULL DEFAULT NULL,
     `tenth_first` int NULL DEFAULT NULL,
     `tenth_second` int NULL DEFAULT NULL,
     `tenth_third` int NULL DEFAULT NULL,
     `tenth_fourth` int NULL DEFAULT NULL,
     `tenth_fifth` int NULL DEFAULT NULL,
     `tenth_sixth` int NULL DEFAULT NULL,
     `tenth_seventh` int NULL DEFAULT NULL,
     `tenth_eighth` int NULL DEFAULT NULL,
     `tenth_ninth` int NULL DEFAULT NULL,
     `tenth_tenth` int NULL DEFAULT NULL,
     `first_big` int NULL DEFAULT NULL,
     `first_small` int NULL DEFAULT NULL,
     `first_odd` int NULL DEFAULT NULL,
     `first_even` int NULL DEFAULT NULL,
     `first_dragon` int NULL DEFAULT NULL,
     `first_tiger` int NULL DEFAULT NULL,
     `second_big` int NULL DEFAULT NULL,
     `second_small` int NULL DEFAULT NULL,
     `second_odd` int NULL DEFAULT NULL,
     `second_even` int NULL DEFAULT NULL,
     `second_dragon` int NULL DEFAULT NULL,
     `second_tiger` int NULL DEFAULT NULL,
     `third_big` int NULL DEFAULT NULL,
     `third_small` int NULL DEFAULT NULL,
     `third_odd` int NULL DEFAULT NULL,
     `third_even` int NULL DEFAULT NULL,
     `third_dragon` int NULL DEFAULT NULL,
     `third_tiger` int NULL DEFAULT NULL,
     `fourth_big` int NULL DEFAULT NULL,
     `fourth_small` int NULL DEFAULT NULL,
     `fourth_odd` int NULL DEFAULT NULL,
     `fourth_even` int NULL DEFAULT NULL,
     `fourth_dragon` int NULL DEFAULT NULL,
     `fourth_tiger` int NULL DEFAULT NULL,
     `fifth_big` int NULL DEFAULT NULL,
     `fifth_small` int NULL DEFAULT NULL,
     `fifth_odd` int NULL DEFAULT NULL,
     `fifth_even` int NULL DEFAULT NULL,
     `fifth_dragon` int NULL DEFAULT NULL,
     `fifth_tiger` int NULL DEFAULT NULL,
     `sixth_big` int NULL DEFAULT NULL,
     `sixth_small` int NULL DEFAULT NULL,
     `sixth_odd` int NULL DEFAULT NULL,
     `sixth_even` int NULL DEFAULT NULL,
     `seventh_big` int NULL DEFAULT NULL,
     `seventh_small` int NULL DEFAULT NULL,
     `seventh_odd` int NULL DEFAULT NULL,
     `seventh_even` int NULL DEFAULT NULL,
     `eighth_big` int NULL DEFAULT NULL,
     `eighth_small` int NULL DEFAULT NULL,
     `eighth_odd` int NULL DEFAULT NULL,
     `eighth_even` int NULL DEFAULT NULL,
     `ninth_big` int NULL DEFAULT NULL,
     `ninth_small` int NULL DEFAULT NULL,
     `ninth_odd` int NULL DEFAULT NULL,
     `ninth_even` int NULL DEFAULT NULL,
     `tenth_big` int NULL DEFAULT NULL,
     `tenth_small` int NULL DEFAULT NULL,
     `tenth_odd` int NULL DEFAULT NULL,
     `tenth_even` int NULL DEFAULT NULL,
     `top_big` int NULL DEFAULT NULL,
     `top_small` int NULL DEFAULT NULL,
     `top_odd` int NULL DEFAULT NULL,
     `top_even` int NULL DEFAULT NULL,
     PRIMARY KEY (`eid`) USING BTREE,
     INDEX `long_dragon_race_id_FK`(`race_id`) USING BTREE,
     CONSTRAINT `long_dragon_race_id_FK` FOREIGN KEY (`race_id`) REFERENCES `fast_car` (`eid`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;
